import {
    MAX_FILE_SIZE,
    ALLOWED_EXT,
    USER_PLACEHOLDER_IMAGE_URL,
    SNACK_PLACEHOLDER_IMAGE_URL,
} from './files.js';
import { COOKIE_OPTIONS, CORS_OPTIONS, WHITELIST } from './options.js';
import {
    OK,
    BAD_REQUEST,
    NOT_FOUND,
    CREATED,
    SERVER_ERROR,
    FORBIDDEN,
} from './errorCodes.js';

export {
    MAX_FILE_SIZE,
    ALLOWED_EXT,
    USER_PLACEHOLDER_IMAGE_URL,
    SNACK_PLACEHOLDER_IMAGE_URL,
    COOKIE_OPTIONS,
    CORS_OPTIONS,
    WHITELIST,
    OK,
    BAD_REQUEST,
    NOT_FOUND,
    CREATED,
    SERVER_ERROR,
    FORBIDDEN,
};
