import { v2 as cloudinary } from 'cloudinary';
import fs from 'fs';

cloudinary.config({
    secure: true,
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
});

/**
 * Util for uploading files on cloudinary using their local paths and deleting them afterwards
 * @param {String} localFilePath - The local path where the files are temporarely stored by multer
 * @returns {String} The url recieved from cloudinary
 */

const uploadOnCloudinary = async (localFilePath) => {
    try {
        if (!localFilePath) {
            throw new Error('local file path missing');
        }

        const result = await cloudinary.uploader.upload(localFilePath, {
            resource_type: 'auto',
        });

        console.log('file uploaded successfully.', result.secure_url);

        return result;
    } catch (err) {
        throw new Error(
            `error while uploading file on cloudinary, ${err.message}`
        );
    } finally {
        fs.unlinkSync(localFilePath);
    }
};

/**
 * Util for deleting files from cloudinary using their URLs (public ids)
 * @param {String} URL - The URL generated by Cloudinary
 * @returns {Object} The delete response recieved from cloudinary
 */

const deleteFromCloudinary = async (URL) => {
    try {
        if (!URL) {
            throw new Error('url missing');
        }

        const publicId = URL.split('/').pop().split('.')[0];
        const resourceType = URL.split('/')[4];

        const res = await cloudinary.uploader.destroy(publicId, {
            resource_type: resourceType,
            invalidate: true,
        });

        return res; // {result:"ok"}
    } catch (err) {
        throw new Error(
            `error while deleting file from cloudinary, err: ${err.message}`
        );
    }
};

export { uploadOnCloudinary, deleteFromCloudinary };
