name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/mern-app
            git pull origin main
            npm install

            # BACKEND
            cd server
            npm install
            pm2 delete snacktrack-backend || true
            pm2 start src/server.js --name snacktrack-backend

            # FRONTEND
            cd ../client
            npm install
            pm2 delete vite || true
            pm2 start "npm run dev -- --host --port 5173" --name vite